// Quest kits — reusable blueprints consumed by quest-generator.js.
//
// A kit declares:
//   - `plants`:       entities to scatter on map nodes, with a `match` predicate.
//   - `buildActions`: grounded STRIPS actions derived from the plantings and map.
//   - `buildGoals`:   disjunctive conjunctive goals; the planner accepts the
//                     first reachable goal.
//
// Travel actions are auto-generated by the generator from the map's DAG edges,
// so kits only need to describe pickup/use/unlock semantics. See
// quest-generator.js for the context object passed to the build functions.

/** True for nodes that can carry a quest item safely (not layer 0, not boss). */
export function nodeIsPlantable(n, map) {
    if (n.type === 'boss') return false;
    if (n.layer === 0) return false;
    if (n.layer === map.layers.length - 2 && n.type === 'camp') return false;
    return true;
}

const KITS = [
    {
        id: 'lost-relic',
        title: 'The Lost Relic',
        description: 'A relic lies abandoned along the path. Carry it to the boss chamber.',
        plants: [
            {
                entity: 'relic',
                label: 'Relic',
                match: (n, map) => nodeIsPlantable(n, map) && (n.type === 'event' || n.type === 'recruit'),
            },
        ],
        buildActions(ctx) {
            const { plantings, map } = ctx;
            const relicId = plantings.relic.nodeId;
            const actions = [];
            for (const layer of map.layers) {
                for (const node of layer) {
                    if (node.id !== relicId) continue;
                    actions.push({
                        name: `Pickup Relic at ${node.id}`,
                        precond: [`at(party,${node.id})`, `at(relic,${node.id})`],
                        add: ['has(party,relic)'],
                        del: [`at(relic,${node.id})`],
                    });
                }
            }
            return actions;
        },
        buildGoals(ctx) {
            return [[`has(party,relic)`, `at(party,${ctx.bossNodeId})`]];
        },
        interferences: [
            { id: 'relic-slips',  label: 'The relic slips from your grasp',
              requires: 'has(party,relic)', remove: ['has(party,relic)'] },
            { id: 'relic-cracks', label: 'A hairline crack spreads across the relic',
              requires: 'has(party,relic)', add: ['damaged(relic)'] },
        ],
        reward(game, deps) {
            const item = deps.pickRandomItem(['uncommon']);
            return deps.giveItemToParty(item, 'The relic you carried proves a minor treasure');
        },
    },

    {
        id: 'locked-vault',
        title: 'The Locked Vault',
        description: 'A sealed vault guards a relic. Find its key and carry the relic to the boss.',
        plants: [
            {
                entity: 'key',
                label: 'Iron Key',
                match: (n, map) => nodeIsPlantable(n, map) && (n.type === 'event' || n.type === 'elite'),
            },
            {
                entity: 'vault',
                label: 'Sealed Vault',
                match: (n, map) => nodeIsPlantable(n, map) && n.type === 'event',
            },
        ],
        buildActions(ctx) {
            const { plantings } = ctx;
            const keyNode   = plantings.key.nodeId;
            const vaultNode = plantings.vault.nodeId;
            return [
                {
                    name: `Pickup Key at ${keyNode}`,
                    precond: [`at(party,${keyNode})`, `at(key,${keyNode})`],
                    add: ['has(party,key)'],
                    del: [`at(key,${keyNode})`],
                },
                {
                    name: `Unlock Vault at ${vaultNode}`,
                    precond: [`at(party,${vaultNode})`, `at(vault,${vaultNode})`, 'has(party,key)'],
                    add: [`unlocked(vault)`],
                    del: [],
                },
                {
                    name: `Take Relic from Vault`,
                    precond: [`at(party,${vaultNode})`, `unlocked(vault)`],
                    add: ['has(party,relic)'],
                    del: [],
                },
            ];
        },
        buildGoals(ctx) {
            return [[`has(party,relic)`, `at(party,${ctx.bossNodeId})`]];
        },
        interferences: [
            { id: 'key-stolen',   label: 'A pickpocket lifts the iron key',
              requires: 'has(party,key)', remove: ['has(party,key)'] },
            { id: 'vault-warded', label: 'A ward crackles across the vault door',
              requires: 'at(vault,$vault)', add: ['warded(vault)'] },
        ],
        reward(game, deps) {
            const item = deps.pickRandomItem(['rare']);
            return deps.giveItemToParty(item, 'The vault\'s relic is an artifact of real power');
        },
    },
];

export function listQuestKitIds() {
    return KITS.map(k => k.id);
}

export function getQuestKit(id) {
    return KITS.find(k => k.id === id) ?? null;
}

export function allQuestKits() {
    return KITS.slice();
}
